
jobs:
  build1:
    docker:
      - image: cyversevice/jupyterlab-qiime2:2019.10
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/jupyterlab-qiime2:2019.7
    steps:
      - checkout
      - run: jupyter lab --version
workflows:
  version: 2
  build1_to_build2:
    jobs:
      - build1
      - build2
